### ISSUE TITLE
Can you add nflstreams and mmastreams

### ISSUE THREAD

**Issue by bob1321** [syco/ACE.bundle#1]
Hello, thank you for your work!!

Can you add: 
https://www.reddit.com/r/nflstreams
https://www.reddit.com/r/MMAStreams/

**Comment by syco** [comment]
I'll have a look, but html scraping is extremely unreliable.
https://www.reddit.com/r/soccerstreams/ is maintained fairly well,
but for example https://www.reddit.com/r/motorsportsstreams/ is really bad.
So if there's any other website you can suggest I'll look into those as well.

**Comment by bob1321** [comment]
Thank you!!

**Comment by bvanwesten** [comment]
/r/nflstreams seems to keep consistent with an @ symbol in each post. I've used this successfully to stream a game from there:

`@route('/video/ace/redditlist')
def RedditList(title):
  oc = ObjectContainer(title2 = title)
  oc.add(
    DirectoryObject(
      key = Callback(RedditList, title = title),
      title = 'Refresh'
    )
  )
  html = HTML.ElementFromURL('https://www.reddit.com/r/nflstreams/')
  for item in html.xpath('//a[.//*[contains(translate(text(), "ABCDEFGHJIKLMNOPQRSTUVWXYZ", "abcdefghjiklmnopqrstuvwxyz"), " @")]]'):
    title = (item.xpath('./h2/text()')[0]).decode('utf-8')
    href = item.get('href');
    oc.add(
      DirectoryObject(
        key = Callback(RedditSubList, title = title, url = href),
        title = title
      )
    )
  return oc`

**Comment by bvanwesten** [comment]
[There is also a fork done by another user that adds CFB and NFL games](https://github.com/zabracks/ACE.bundle/blob/master/Contents/Code/__init__.py).

**Comment by syco** [comment]
I've added the nfl streams using the " @" as you suggested, but I can't test it unless I catch the page when there's a match on.

**Comment by bvanwesten** [comment]
> I've added the nfl streams using the " @" as you suggested, but I can't test it unless I catch the page when there's a match on.

I tested it with tonight's Thursday Night game, and it worked in Chrome 👍

**Comment by bob1321** [comment]
Is it possible to add NBA too :)
https://www.reddit.com/r/nbastreams/

Thank you for your excellent job

**Comment by syco** [comment]
I can't see any match in the nba page. I've added it with a generic 'vs' separator, please reopen the issue if it doesn't work as expected.
Thanks.

**Comment by bob1321** [comment]
in nbastreams its a @ for the separator.

Thank you!!
