### ISSUE TITLE
Arenavision alternative

### ISSUE THREAD

**Issue by xaxeu** [syco/ACE.bundle#10]
Hi,

Can you have a look to this site and see if it's possible to scrap?

https://avezy.xyz/

Thanks!

**Comment by mjs00000** [comment]
Footbite.com (soccer streams) as a possible parser, if it can be done...?

**Comment by syco** [comment]
thanks both, but...
avezy.xyz is a mirror of arenavision
footybite doesn't do acestream, they use the blob:http that can't be scraped as far as I know..
