### ISSUE TITLE
Adding LiveTVLinks 

### ISSUE THREAD

**Issue by gaussey** [syco/ACE.bundle#11]
**Reddit**
Any chance you can add /r/livetvlinks ?

Also, adding the ability to add our own playlist of stream links would help futureproof this a bit.

**Comment by syco** [comment]
Hi,
I'll add this to the php scrapers in the next couple of days.
If you are using the latest version of this plugin it will appear in the automatically.

**Comment by gaussey** [comment]
Thanks :)
