### ISSUE TITLE
Configurable Ace engine path

### ISSUE THREAD

**Issue by Jayphen** [syco/ACE.bundle#12]
It seems that the ace engine path is hard coded at the moment, with only the host and port configurable. It would be nice to be able to configure the entire path.

Currently the path is:

`url = 'http://{}:{}/ace/manifest.m3u8?id={}'.format(Prefs['ace_host'], Prefs['ace_port'], phpscraper['link']),`

I am using https://github.com/ikatson/docker-acestream-proxy, which requires paths to be in the form
`http://[SERVER_IP]:8000/pid/{channel_id}/stream.mp4`

(alternatively, I'd love to be pointed in the direction of a different acestream proxy that runs in docker)

**Comment by syco** [comment]
Hi,
I published the docker image I use, it's very simple: `docker run -it --rm -P sycolth/acestream`
you can see the dockerfile here : https://github.com/syco/acestream

**Comment by Jayphen** [comment]
@syco Thank you, I will switch to using that :)
