### ISSUE TITLE
http://acesoplisting.in

### ISSUE THREAD

**Issue by gaussey** [syco/ACE.bundle#13]
**Reddit**
Please attach screenshots showing the title of the posts that need to be scraped.

**Not Reddit**
..just name the website, I'll have a look myself.. ;)

http://acesoplisting.in/

**Comment by syco** [comment]
http://acesoplisting.in is another mirror of arenavision, just like https://acelisting.in
I recentlly moved the scrapers to a php script hosted online, this ihas been done for a number of reasons:
it makes it easier to provision new sources
plex plugins are very badly documented
plex plugins will actually be removed very soon
I believe php it's a better language than python

Anyway, have a look at the php scrapers and see if acelisting is an acceptable alternative.
