### ISSUE TITLE
Video Never starts to play

### ISSUE THREAD

**Issue by antooro** [syco/ACE.bundle#14]
i execute 

acestreamengine --log-stdout --client-console

on my ubuntu 16. machine, 

then it says 
acestream.SocketHandler.SocketHandler|bind: socket bound: host=127.0.0.1 port=62062

so i set 62062 to the port in the plugin config

I click in one stream but it never starts.
What am i missing?

![](https://i.imgur.com/hJO4zIk.png)

**Comment by syco** [comment]
Hi,
that's not the default port, you actually want port 6878 ;)

**Comment by antooro** [comment]
I tried with default port, nothing seems to happen in the cli acestreamengine
