### ISSUE TITLE
Doesn't work since soccer_streams have changed reddit location

### ISSUE THREAD

**Issue by mjs00000** [syco/ACE.bundle#8]
Server doesn't open steams via ace stream engine. Is anyone else having this issue?

**Comment by syco** [comment]
Hi,
I've updated the url a week ago, please update your installation.

**Comment by mjs00000** [comment]
Thanks for replying Alberto.

I am running your latest version, but when clicking on the available
streams which are scrapped, the Plex plug-in doesn't open within the ace
stream engine.

I can see this within the logs and server status.

Is anyone else having issues that you know?


Regards,

MJS

**Comment by syco** [comment]
Did you configure the plugin with the ip address and port of the acestream server?
can you post the file syco.plex.acestream.log ? maybe there's something there..

**Comment by mjs00000** [comment]
Yes default ip: 127.0.0.1  port:6878

**Comment by mjs00000** [comment]
[syco.plex.acestream.log](https://github.com/syco/ACE.bundle/files/2813480/syco.plex.acestream.log)

**Comment by mjs00000** [comment]
2019-01-28 19:46:47,726 (ba4) :  WARNING (objectkit:208) - Media part has no streams - attempting to synthesize

It's this line which I'm confused by...

**Comment by syco** [comment]
A few days ago I introduced a change in the mediaobject, maybe that's the problem.
I just pushed an update to revert this change. Can you please test again?

**Comment by mjs00000** [comment]
Thanks for the prompt response. I have just tested it briefly with a soccer stream that was open - it seems to work fine :)

I'll test it again at the weekend and report back. For now though, do you have a donate option? Your plugin is a lifesaver!

Keep up the hard work! Thank you.

**Comment by syco** [comment]
I never believed too much in donate buttons, but since you asked I added one, thanks anyway for using the plugin and report issues.
I guess this one is solved.
